version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: yarn start
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8080:8080
