version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: yarn start -- --host
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 8080:8080
